// Code generated by protoc-gen-go. DO NOT EDIT.
// source: moc_cloudagent_publicipaddress.proto

package network

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	common "github.com/microsoft/moc/rpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PublicIPAddressRequest struct {
	PublicIPAddresses    []*PublicIPAddress `protobuf:"bytes,1,rep,name=PublicIPAddresses,proto3" json:"PublicIPAddresses,omitempty"`
	OperationType        common.Operation   `protobuf:"varint,2,opt,name=OperationType,proto3,enum=moc.Operation" json:"OperationType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PublicIPAddressRequest) Reset()         { *m = PublicIPAddressRequest{} }
func (m *PublicIPAddressRequest) String() string { return proto.CompactTextString(m) }
func (*PublicIPAddressRequest) ProtoMessage()    {}
func (*PublicIPAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35bf7f9bc887fae5, []int{0}
}

func (m *PublicIPAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicIPAddressRequest.Unmarshal(m, b)
}
func (m *PublicIPAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicIPAddressRequest.Marshal(b, m, deterministic)
}
func (m *PublicIPAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicIPAddressRequest.Merge(m, src)
}
func (m *PublicIPAddressRequest) XXX_Size() int {
	return xxx_messageInfo_PublicIPAddressRequest.Size(m)
}
func (m *PublicIPAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicIPAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublicIPAddressRequest proto.InternalMessageInfo

func (m *PublicIPAddressRequest) GetPublicIPAddresses() []*PublicIPAddress {
	if m != nil {
		return m.PublicIPAddresses
	}
	return nil
}

func (m *PublicIPAddressRequest) GetOperationType() common.Operation {
	if m != nil {
		return m.OperationType
	}
	return common.Operation_GET
}

type PublicIPAddressResponse struct {
	PublicIPAddresses    []*PublicIPAddress  `protobuf:"bytes,1,rep,name=PublicIPAddresses,proto3" json:"PublicIPAddresses,omitempty"`
	Result               *wrappers.BoolValue `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                string              `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PublicIPAddressResponse) Reset()         { *m = PublicIPAddressResponse{} }
func (m *PublicIPAddressResponse) String() string { return proto.CompactTextString(m) }
func (*PublicIPAddressResponse) ProtoMessage()    {}
func (*PublicIPAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35bf7f9bc887fae5, []int{1}
}

func (m *PublicIPAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicIPAddressResponse.Unmarshal(m, b)
}
func (m *PublicIPAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicIPAddressResponse.Marshal(b, m, deterministic)
}
func (m *PublicIPAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicIPAddressResponse.Merge(m, src)
}
func (m *PublicIPAddressResponse) XXX_Size() int {
	return xxx_messageInfo_PublicIPAddressResponse.Size(m)
}
func (m *PublicIPAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicIPAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublicIPAddressResponse proto.InternalMessageInfo

func (m *PublicIPAddressResponse) GetPublicIPAddresses() []*PublicIPAddress {
	if m != nil {
		return m.PublicIPAddresses
	}
	return nil
}

func (m *PublicIPAddressResponse) GetResult() *wrappers.BoolValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *PublicIPAddressResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type PublicIPAddressPrecheckRequest struct {
	PublicIPAddresses    []*PublicIPAddress `protobuf:"bytes,1,rep,name=PublicIPAddresses,proto3" json:"PublicIPAddresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PublicIPAddressPrecheckRequest) Reset()         { *m = PublicIPAddressPrecheckRequest{} }
func (m *PublicIPAddressPrecheckRequest) String() string { return proto.CompactTextString(m) }
func (*PublicIPAddressPrecheckRequest) ProtoMessage()    {}
func (*PublicIPAddressPrecheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35bf7f9bc887fae5, []int{2}
}

func (m *PublicIPAddressPrecheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicIPAddressPrecheckRequest.Unmarshal(m, b)
}
func (m *PublicIPAddressPrecheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicIPAddressPrecheckRequest.Marshal(b, m, deterministic)
}
func (m *PublicIPAddressPrecheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicIPAddressPrecheckRequest.Merge(m, src)
}
func (m *PublicIPAddressPrecheckRequest) XXX_Size() int {
	return xxx_messageInfo_PublicIPAddressPrecheckRequest.Size(m)
}
func (m *PublicIPAddressPrecheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicIPAddressPrecheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublicIPAddressPrecheckRequest proto.InternalMessageInfo

func (m *PublicIPAddressPrecheckRequest) GetPublicIPAddresses() []*PublicIPAddress {
	if m != nil {
		return m.PublicIPAddresses
	}
	return nil
}

type PublicIPAddressPrecheckResponse struct {
	// The precheck result: true if the precheck criteria is passed; otherwise, false
	Result *wrappers.BoolValue `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	// The error message if the precheck is not passed; otherwise, empty string
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicIPAddressPrecheckResponse) Reset()         { *m = PublicIPAddressPrecheckResponse{} }
func (m *PublicIPAddressPrecheckResponse) String() string { return proto.CompactTextString(m) }
func (*PublicIPAddressPrecheckResponse) ProtoMessage()    {}
func (*PublicIPAddressPrecheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35bf7f9bc887fae5, []int{3}
}

func (m *PublicIPAddressPrecheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicIPAddressPrecheckResponse.Unmarshal(m, b)
}
func (m *PublicIPAddressPrecheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicIPAddressPrecheckResponse.Marshal(b, m, deterministic)
}
func (m *PublicIPAddressPrecheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicIPAddressPrecheckResponse.Merge(m, src)
}
func (m *PublicIPAddressPrecheckResponse) XXX_Size() int {
	return xxx_messageInfo_PublicIPAddressPrecheckResponse.Size(m)
}
func (m *PublicIPAddressPrecheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicIPAddressPrecheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublicIPAddressPrecheckResponse proto.InternalMessageInfo

func (m *PublicIPAddressPrecheckResponse) GetResult() *wrappers.BoolValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *PublicIPAddressPrecheckResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type PublicIPAddress struct {
	Name                 string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string                    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	IpAddress            string                    `protobuf:"bytes,3,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	Allocation           common.IPAllocationMethod `protobuf:"varint,4,opt,name=allocation,proto3,enum=moc.IPAllocationMethod" json:"allocation,omitempty"`
	IpVersion            common.IPVersion          `protobuf:"varint,5,opt,name=ipVersion,proto3,enum=moc.IPVersion" json:"ipVersion,omitempty"`
	IdleTimeoutInMinutes uint32                    `protobuf:"varint,6,opt,name=idleTimeoutInMinutes,proto3" json:"idleTimeoutInMinutes,omitempty"`
	DomainNameLabel      string                    `protobuf:"bytes,7,opt,name=domainNameLabel,proto3" json:"domainNameLabel,omitempty"`
	Fqdn                 string                    `protobuf:"bytes,8,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	ReverseFqdn          string                    `protobuf:"bytes,9,opt,name=reverseFqdn,proto3" json:"reverseFqdn,omitempty"`
	LocationName         string                    `protobuf:"bytes,10,opt,name=locationName,proto3" json:"locationName,omitempty"`
	Status               *common.Status            `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	Tags                 *common.Tags              `protobuf:"bytes,12,opt,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PublicIPAddress) Reset()         { *m = PublicIPAddress{} }
func (m *PublicIPAddress) String() string { return proto.CompactTextString(m) }
func (*PublicIPAddress) ProtoMessage()    {}
func (*PublicIPAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_35bf7f9bc887fae5, []int{4}
}

func (m *PublicIPAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicIPAddress.Unmarshal(m, b)
}
func (m *PublicIPAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicIPAddress.Marshal(b, m, deterministic)
}
func (m *PublicIPAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicIPAddress.Merge(m, src)
}
func (m *PublicIPAddress) XXX_Size() int {
	return xxx_messageInfo_PublicIPAddress.Size(m)
}
func (m *PublicIPAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicIPAddress.DiscardUnknown(m)
}

var xxx_messageInfo_PublicIPAddress proto.InternalMessageInfo

func (m *PublicIPAddress) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PublicIPAddress) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PublicIPAddress) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *PublicIPAddress) GetAllocation() common.IPAllocationMethod {
	if m != nil {
		return m.Allocation
	}
	return common.IPAllocationMethod_Invalid
}

func (m *PublicIPAddress) GetIpVersion() common.IPVersion {
	if m != nil {
		return m.IpVersion
	}
	return common.IPVersion_IPv4
}

func (m *PublicIPAddress) GetIdleTimeoutInMinutes() uint32 {
	if m != nil {
		return m.IdleTimeoutInMinutes
	}
	return 0
}

func (m *PublicIPAddress) GetDomainNameLabel() string {
	if m != nil {
		return m.DomainNameLabel
	}
	return ""
}

func (m *PublicIPAddress) GetFqdn() string {
	if m != nil {
		return m.Fqdn
	}
	return ""
}

func (m *PublicIPAddress) GetReverseFqdn() string {
	if m != nil {
		return m.ReverseFqdn
	}
	return ""
}

func (m *PublicIPAddress) GetLocationName() string {
	if m != nil {
		return m.LocationName
	}
	return ""
}

func (m *PublicIPAddress) GetStatus() *common.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *PublicIPAddress) GetTags() *common.Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*PublicIPAddressRequest)(nil), "moc.cloudagent.network.PublicIPAddressRequest")
	proto.RegisterType((*PublicIPAddressResponse)(nil), "moc.cloudagent.network.PublicIPAddressResponse")
	proto.RegisterType((*PublicIPAddressPrecheckRequest)(nil), "moc.cloudagent.network.PublicIPAddressPrecheckRequest")
	proto.RegisterType((*PublicIPAddressPrecheckResponse)(nil), "moc.cloudagent.network.PublicIPAddressPrecheckResponse")
	proto.RegisterType((*PublicIPAddress)(nil), "moc.cloudagent.network.PublicIPAddress")
}

func init() {
	proto.RegisterFile("moc_cloudagent_publicipaddress.proto", fileDescriptor_35bf7f9bc887fae5)
}

var fileDescriptor_35bf7f9bc887fae5 = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xfd, 0x9c, 0xa6, 0xf9, 0x9a, 0x9b, 0xfe, 0x88, 0x51, 0xd5, 0x5a, 0x91, 0x28, 0x91, 0x41,
	0x22, 0x0b, 0x64, 0x8b, 0x80, 0xe8, 0xba, 0x95, 0x40, 0x8a, 0x44, 0x21, 0x1a, 0x4a, 0x17, 0x6c,
	0xaa, 0x89, 0x7d, 0x9b, 0x8e, 0x62, 0xfb, 0xba, 0x33, 0xe3, 0x56, 0x2c, 0xd8, 0xb0, 0xe2, 0x45,
	0x78, 0x04, 0x36, 0x88, 0x87, 0x43, 0x1e, 0x3b, 0x4d, 0xea, 0x16, 0x29, 0x5d, 0x74, 0xe5, 0xf1,
	0x3d, 0xe7, 0x9e, 0xb9, 0x3f, 0x67, 0xe0, 0x59, 0x42, 0xe1, 0x69, 0x18, 0x53, 0x1e, 0x89, 0x09,
	0xa6, 0xe6, 0x34, 0xcb, 0xc7, 0xb1, 0x0c, 0x65, 0x26, 0xa2, 0x48, 0xa1, 0xd6, 0x7e, 0xa6, 0xc8,
	0x10, 0xdb, 0x49, 0x28, 0xf4, 0xe7, 0x2c, 0x3f, 0x45, 0x73, 0x45, 0x6a, 0xda, 0xdd, 0x9b, 0x10,
	0x4d, 0x62, 0x0c, 0x2c, 0x6b, 0x9c, 0x9f, 0x05, 0x57, 0x4a, 0x64, 0x19, 0xaa, 0x2a, 0xaf, 0xbb,
	0x6b, 0xd5, 0x29, 0x49, 0x28, 0xad, 0x3e, 0x15, 0xb0, 0xb7, 0x00, 0x54, 0x62, 0x8b, 0xb8, 0xf7,
	0xd3, 0x81, 0x9d, 0x91, 0x2d, 0x65, 0x38, 0x3a, 0x28, 0x4b, 0xe1, 0x78, 0x91, 0xa3, 0x36, 0xec,
	0x33, 0x3c, 0xaa, 0x21, 0xa8, 0x5d, 0xa7, 0xb7, 0xd2, 0xef, 0x0c, 0x9e, 0xfb, 0x77, 0xd7, 0xe9,
	0xd7, 0xa5, 0x6e, 0x2b, 0xb0, 0xd7, 0xb0, 0xf1, 0x31, 0x43, 0x25, 0x8c, 0xa4, 0xf4, 0xf8, 0x6b,
	0x86, 0x6e, 0xa3, 0xe7, 0xf4, 0x37, 0x07, 0x9b, 0x56, 0xf2, 0x1a, 0xe1, 0x37, 0x49, 0xde, 0x6f,
	0x07, 0x76, 0x6f, 0xd5, 0xa9, 0x33, 0x4a, 0x35, 0x3e, 0x54, 0xa1, 0x03, 0x68, 0x71, 0xd4, 0x79,
	0x6c, 0x6c, 0x85, 0x9d, 0x41, 0xd7, 0x2f, 0x97, 0xe0, 0xcf, 0x96, 0xe0, 0x1f, 0x12, 0xc5, 0x27,
	0x22, 0xce, 0x91, 0x57, 0x4c, 0xb6, 0x0d, 0xab, 0x6f, 0x95, 0x22, 0xe5, 0xae, 0xf4, 0x9c, 0x7e,
	0x9b, 0x97, 0x3f, 0xde, 0x15, 0xec, 0xd5, 0xe4, 0x47, 0x0a, 0xc3, 0x73, 0x0c, 0xa7, 0x0f, 0x3b,
	0x6b, 0x6f, 0x0a, 0x4f, 0xfe, 0x79, 0x71, 0x35, 0xbc, 0x79, 0x97, 0xce, 0xfd, 0xbb, 0x6c, 0x2c,
	0x76, 0xf9, 0x67, 0x05, 0xb6, 0x6a, 0xb7, 0x31, 0x06, 0xcd, 0x54, 0x24, 0x68, 0xb5, 0xdb, 0xdc,
	0x9e, 0xd9, 0x26, 0x34, 0x64, 0x54, 0xa5, 0x36, 0x64, 0xc4, 0x3c, 0x68, 0xcb, 0xac, 0x4a, 0x28,
	0xe7, 0x76, 0xd8, 0xfc, 0xf1, 0xcb, 0x75, 0xf8, 0x3c, 0xcc, 0xf6, 0x01, 0x44, 0x1c, 0x53, 0x68,
	0x0d, 0xe1, 0x36, 0xad, 0x63, 0x76, 0xed, 0x60, 0x86, 0xa3, 0x83, 0x6b, 0xe0, 0x08, 0xcd, 0x39,
	0x45, 0x7c, 0x81, 0xca, 0x5e, 0x14, 0xe2, 0x27, 0xa8, 0x74, 0x91, 0xb7, 0xba, 0xe0, 0xb4, 0xe1,
	0xa8, 0x8a, 0xf2, 0x39, 0x81, 0x0d, 0x60, 0x5b, 0x46, 0x31, 0x1e, 0xcb, 0x04, 0x29, 0x37, 0xc3,
	0xf4, 0x48, 0xa6, 0xb9, 0x41, 0xed, 0xb6, 0x7a, 0x4e, 0x7f, 0x83, 0xdf, 0x89, 0xb1, 0x3e, 0x6c,
	0x45, 0x94, 0x08, 0x99, 0x7e, 0x10, 0x09, 0xbe, 0x17, 0x63, 0x8c, 0xdd, 0xff, 0x6d, 0x6f, 0xf5,
	0x70, 0x31, 0x8c, 0xb3, 0x8b, 0x28, 0x75, 0xd7, 0xca, 0x61, 0x14, 0x67, 0xd6, 0x83, 0x8e, 0xc2,
	0x4b, 0x54, 0x1a, 0xdf, 0x15, 0x50, 0xdb, 0x42, 0x8b, 0x21, 0xe6, 0xc1, 0xfa, 0xac, 0x9b, 0x42,
	0xca, 0x05, 0x4b, 0xb9, 0x11, 0x63, 0x4f, 0xa1, 0xa5, 0x8d, 0x30, 0xb9, 0x76, 0x3b, 0x76, 0x89,
	0x1d, 0xdb, 0xe2, 0x27, 0x1b, 0xe2, 0x15, 0xc4, 0x1e, 0x43, 0xd3, 0x88, 0x89, 0x76, 0xd7, 0x2d,
	0xa5, 0x6d, 0x29, 0xc7, 0x62, 0xa2, 0xb9, 0x0d, 0x0f, 0xbe, 0x37, 0x60, 0xbb, 0xb6, 0xbe, 0x83,
	0xc2, 0x6f, 0x6c, 0x0a, 0xad, 0x61, 0x7a, 0x49, 0x53, 0x64, 0xfe, 0xb2, 0x56, 0x2c, 0x5d, 0xdd,
	0x0d, 0x96, 0xe6, 0x97, 0x66, 0xf4, 0xfe, 0x63, 0xdf, 0x60, 0x6d, 0x66, 0x51, 0xf6, 0x66, 0xc9,
	0xf4, 0xda, 0x63, 0xea, 0xee, 0xdf, 0x3b, 0x6f, 0x76, 0xfd, 0xe1, 0xcb, 0x2f, 0xc1, 0x44, 0x9a,
	0xf3, 0x7c, 0xec, 0x87, 0x94, 0x04, 0x89, 0x0c, 0x15, 0x69, 0x3a, 0x33, 0x41, 0x42, 0x61, 0xa0,
	0xb2, 0x30, 0x98, 0x8b, 0x06, 0x95, 0xe8, 0xb8, 0x65, 0x1f, 0xca, 0xab, 0xbf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x02, 0xb2, 0xef, 0x88, 0xe1, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PublicIPAddressAgentClient is the client API for PublicIPAddressAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PublicIPAddressAgentClient interface {
	Invoke(ctx context.Context, in *PublicIPAddressRequest, opts ...grpc.CallOption) (*PublicIPAddressResponse, error)
	// Prechecks whether the system is able to create specified public IP address (but does not actually create them).
	Precheck(ctx context.Context, in *PublicIPAddressPrecheckRequest, opts ...grpc.CallOption) (*PublicIPAddressPrecheckResponse, error)
}

type publicIPAddressAgentClient struct {
	cc *grpc.ClientConn
}

func NewPublicIPAddressAgentClient(cc *grpc.ClientConn) PublicIPAddressAgentClient {
	return &publicIPAddressAgentClient{cc}
}

func (c *publicIPAddressAgentClient) Invoke(ctx context.Context, in *PublicIPAddressRequest, opts ...grpc.CallOption) (*PublicIPAddressResponse, error) {
	out := new(PublicIPAddressResponse)
	err := c.cc.Invoke(ctx, "/moc.cloudagent.network.PublicIPAddressAgent/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicIPAddressAgentClient) Precheck(ctx context.Context, in *PublicIPAddressPrecheckRequest, opts ...grpc.CallOption) (*PublicIPAddressPrecheckResponse, error) {
	out := new(PublicIPAddressPrecheckResponse)
	err := c.cc.Invoke(ctx, "/moc.cloudagent.network.PublicIPAddressAgent/Precheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicIPAddressAgentServer is the server API for PublicIPAddressAgent service.
type PublicIPAddressAgentServer interface {
	Invoke(context.Context, *PublicIPAddressRequest) (*PublicIPAddressResponse, error)
	// Prechecks whether the system is able to create specified public IP address (but does not actually create them).
	Precheck(context.Context, *PublicIPAddressPrecheckRequest) (*PublicIPAddressPrecheckResponse, error)
}

// UnimplementedPublicIPAddressAgentServer can be embedded to have forward compatible implementations.
type UnimplementedPublicIPAddressAgentServer struct {
}

func (*UnimplementedPublicIPAddressAgentServer) Invoke(ctx context.Context, req *PublicIPAddressRequest) (*PublicIPAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (*UnimplementedPublicIPAddressAgentServer) Precheck(ctx context.Context, req *PublicIPAddressPrecheckRequest) (*PublicIPAddressPrecheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Precheck not implemented")
}

func RegisterPublicIPAddressAgentServer(s *grpc.Server, srv PublicIPAddressAgentServer) {
	s.RegisterService(&_PublicIPAddressAgent_serviceDesc, srv)
}

func _PublicIPAddressAgent_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicIPAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicIPAddressAgentServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.cloudagent.network.PublicIPAddressAgent/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicIPAddressAgentServer).Invoke(ctx, req.(*PublicIPAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicIPAddressAgent_Precheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicIPAddressPrecheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicIPAddressAgentServer).Precheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.cloudagent.network.PublicIPAddressAgent/Precheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicIPAddressAgentServer).Precheck(ctx, req.(*PublicIPAddressPrecheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PublicIPAddressAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moc.cloudagent.network.PublicIPAddressAgent",
	HandlerType: (*PublicIPAddressAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _PublicIPAddressAgent_Invoke_Handler,
		},
		{
			MethodName: "Precheck",
			Handler:    _PublicIPAddressAgent_Precheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moc_cloudagent_publicipaddress.proto",
}
